# Generated by Django 4.1.1 on 2022-09-21 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('JS', 'Javascript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('PY', 'Python'), ('NJS', 'Node.js')], default='JS', max_length=10)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('date', models.DateField(verbose_name='error date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.TextField()),
                ('date', models.DateField(verbose_name='comment date')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.error')),
            ],
        ),
    ]
